apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: payment-service
  labels:
    app.kubernetes.io/name: payment-microservice
    app.kubernetes.io/component: config
data:
  PORT: "3000"
  NODE_ENV: "production"
  PAYMENT_CURRENCY: "IDR"
  JWT_EXPIRES_IN: "1h"
  SERVICE_NAME: "payment-microservice"
  SERVICE_VERSION: "1.0.0"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.alloy.svc.cluster.local:4318"
  LOKI_HOST: "http://loki.loki.svc.cluster.local:3100"
  CORS_ALLOWED_ORIGINS: "https://dash.sxdentrypoint.my.id,https://app.sxdentrypoint.my.id"
