apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace target untuk seluruh resource (Deployment, Service, dll)
namespace: payment-service

resources:
  - namespace.yaml
  - sa.yaml
  - registry-secret.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

# Label otomatis yang akan disuntikkan ke semua resource dan selector
commonLabels:
  app.kubernetes.io/name: payment-microservice
  app.kubernetes.io/managed-by: kustomize
