apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  namespace: payment-service
  labels:
    app.kubernetes.io/name: payment-microservice
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
