apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment-service
  labels:
    app.kubernetes.io/name: payment-microservice
    app.kubernetes.io/component: secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmRlRTYwMnkwVWNvM0BwYXltZW50LXBvc3RncmVzLWhlYWRsZXNzLnBheW1lbnQtcG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9wYXltZW50X2Ri
  JWT_SECRET: Y2VmOTA2YWEyZThhZDA4ZDliN2U1NGQwZmU3NWU5OTY3MDc5MjU1ZDAzNzI0MWIwMTJjODVjMTYyZDBlMTJmZjljYWQwNWQwZDc5OGY0ZjQ2MzdlNjU1NWE5NDYwNGYxMzQyYWQwNjNhMzcwODg3ZDIwYzhmMzc0ZWMyMGJiNGI=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: QWRtaW5AMTIzNCE=
  ORDER_SERVICE_URL:       aHR0cDovL29yZGVyLXNlcnZpY2Uub3JkZXItc2VydmljZS5zdmMuY2x1c3Rlci5sb2NhbA==
  INTERNAL_SERVICE_SECRET: ZDk5ZDA2YWRkZDNmMGNiNTJhMTEzOGExNzMyN2IzZGQxY2M3M2M3YWY2MDRkNjBlZWIxOTM4MzM2MzliY2Ri
